// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrTIJHZsJRPyI0XWSHpbkT58Ubtu7EOsA',
    appId: '1:1047021906481:android:e27381d8fecd4d9d7a8310',
    messagingSenderId: '1047021906481',
    projectId: 'mynotes-flutter-h-project',
    storageBucket: 'mynotes-flutter-h-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk1YsIEOMFXEVzhWNrqFO-q9dixmp6dgU',
    appId: '1:1047021906481:ios:c99bb8ae419f5b857a8310',
    messagingSenderId: '1047021906481',
    projectId: 'mynotes-flutter-h-project',
    storageBucket: 'mynotes-flutter-h-project.appspot.com',
    iosClientId: '1047021906481-h4ll0qq5cbddk4i5luf4ramaqtg63g33.apps.googleusercontent.com',
    iosBundleId: 'com.huangsri.mynotes',
  );
}
